version: "3"
services:
 rabbitmq:
  image: "rabbitmq:3-management"
  ports:
    - "5672:5672"
    - "15672:15672"
    - "61613:61613"
  volumes:
    - "./.docker/rabbitmq/etc/:/etc/rabbitmq/"
    - "./.docker/rabbitmq/data/:/var/lib/rabbitmq/mnesia"
    - "./.docker/rabbitmq/logs/:/var/log/rabbitmq/"
